# Configuration for https://goreleaser.com/
project_name: injector

release:
  github:
    owner: jonnylangefeld
    name: injector
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
