name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yml
    secrets: inherit
  release:
    name: Release
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
